LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE =
LOCAL_MODULE = MTKLogger
LOCAL_MODULE_CLASS = APPS
LOCAL_MODULE_PATH =
LOCAL_MODULE_RELATIVE_PATH =
LOCAL_MODULE_SUFFIX = .apk
LOCAL_CERTIFICATE = platform
LOCAL_SRC_FILES = MTKLogger.apk
include $(BUILD_PREBUILT)
