/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */
{RIL_REQUEST_GET_COLP, voidToParcel},
{RIL_REQUEST_SET_COLP, intsToParcel},
{RIL_REQUEST_GET_COLR, voidToParcel},
{RIL_REQUEST_GET_CCM, voidToParcel},
{RIL_REQUEST_GET_ACM, voidToParcel},
{RIL_REQUEST_GET_ACMMAX, voidToParcel},
{RIL_REQUEST_GET_PPU_AND_CURRENCY, voidToParcel},
{RIL_REQUEST_SET_ACMMAX, stringsToParcel},
{RIL_REQUEST_RESET_ACM, stringToParcel},
{RIL_REQUEST_SET_PPU_AND_CURRENCY, stringsToParcel},
{RIL_REQUEST_MODEM_POWEROFF, voidToParcel},
{RIL_REQUEST_DUAL_SIM_MODE_SWITCH, intsToParcel},
{RIL_REQUEST_QUERY_PHB_STORAGE_INFO, intsToParcel},
{RIL_REQUEST_WRITE_PHB_ENTRY, phbEntryToParcel},
{RIL_REQUEST_READ_PHB_ENTRY, intsToParcel},
{RIL_REQUEST_SET_GPRS_CONNECT_TYPE, intsToParcel},
{RIL_REQUEST_SET_GPRS_TRANSFER_TYPE, intsToParcel},
{RIL_REQUEST_MOBILEREVISION_AND_IMEI, intsToParcel},
{RIL_REQUEST_QUERY_SIM_NETWORK_LOCK, intsToParcel},
{RIL_REQUEST_SET_SIM_NETWORK_LOCK, stringsToParcel},
{RIL_REQUEST_SET_SCRI, intsToParcel},
{RIL_REQUEST_BTSIM_CONNECT, voidToParcel},
{RIL_REQUEST_BTSIM_DISCONNECT_OR_POWEROFF, stringToParcel},
{RIL_REQUEST_BTSIM_POWERON_OR_RESETSIM, stringsToParcel},
{RIL_REQUEST_BTSIM_TRANSFERAPDU, stringsToParcel},
{RIL_REQUEST_SET_NETWORK_SELECTION_MANUAL_WITH_ACT, stringsToParcel},
{RIL_REQUEST_QUERY_ICCID, voidToParcel},
{RIL_REQUEST_USIM_AUTHENTICATION, stringsToParcel},
{RIL_REQUEST_MODEM_POWERON, voidToParcel},
{RIL_REQUEST_GET_SMS_SIM_MEM_STATUS, voidToParcel},
{RIL_REQUEST_GET_PHONE_CAPABILITY, voidToParcel},
{RIL_REQUEST_SET_PHONE_CAPABILITY, intsToParcel},
{RIL_REQUEST_GET_POL_CAPABILITY, voidToParcel},
{RIL_REQUEST_GET_POL_LIST, voidToParcel},
{RIL_REQUEST_SET_POL_ENTRY, stringsToParcel},
{RIL_REQUEST_QUERY_UPB_CAPABILITY, voidToParcel},
{RIL_REQUEST_EDIT_UPB_ENTRY, stringsToParcel},
{RIL_REQUEST_DELETE_UPB_ENTRY, intsToParcel},
{RIL_REQUEST_READ_UPB_GAS_LIST, intsToParcel},
{RIL_REQUEST_READ_UPB_GRP, intsToParcel},
{RIL_REQUEST_WRITE_UPB_GRP, intsToParcel},
{RIL_REQUEST_SET_SIM_RECOVERY_ON, intsToParcel},
{RIL_REQUEST_GET_SIM_RECOVERY_ON, voidToParcel},
{RIL_REQUEST_SET_TRM, intsToParcel},
{RIL_REQUEST_DETECT_SIM_MISSING, voidToParcel},
{RIL_REQUEST_GET_CALIBRATION_DATA, voidToParcel},
{RIL_REQUEST_GET_PHB_STRING_LENGTH, voidToParcel},
{RIL_REQUEST_GET_PHB_MEM_STORAGE, voidToParcel},
{RIL_REQUEST_SET_PHB_MEM_STORAGE, stringsToParcel},
{RIL_REQUEST_READ_PHB_ENTRY_EXT, intsToParcel},
{RIL_REQUEST_WRITE_PHB_ENTRY_EXT, writePhbEntryExtToParcel},
{RIL_REQUEST_GET_SMS_PARAMS, voidToParcel},
{RIL_REQUEST_SET_SMS_PARAMS, smsParamsToParcel},
{RIL_REQUEST_SIM_TRANSMIT_BASIC, sim_IOToParcel},
{RIL_REQUEST_SIM_TRANSMIT_CHANNEL, sim_IOToParcel},
{RIL_REQUEST_SIM_GET_ATR, voidToParcel},
{RIL_REQUEST_SET_CB_CHANNEL_CONFIG_INFO, stringsToParcel},
{RIL_REQUEST_SET_CB_LANGUAGE_CONFIG_INFO, stringToParcel},
{RIL_REQUEST_GET_CB_CONFIG_INFO, voidToParcel},
{RIL_REQUEST_SET_ALL_CB_LANGUAGE_ON, voidToParcel},
{RIL_REQUEST_SET_ETWS, intsToParcel},
{RIL_REQUEST_SET_FD_MODE, fd_ModeToParcel},
{RIL_REQUEST_DETACH_PS, voidToParcel},
{RIL_REQUEST_SIM_OPEN_CHANNEL_WITH_SW, stringToParcel},
/// M: [C2K][IR] Support SVLTE IR feature. @{
{RIL_REQUEST_SET_REG_SUSPEND_ENABLED, intsToParcel},
{RIL_REQUEST_RESUME_REGISTRATION, intsToParcel},
/// M: [C2K][IR] Support SVLTE IR feature. @}
{RIL_REQUEST_STORE_MODEM_TYPE, intsToParcel},
{RIL_REQUEST_QUERY_MODEM_TYPE, voidToParcel},
{RIL_REQUEST_SIM_INTERFACE_SWITCH, intsToParcel},
{RIL_REQUEST_UICC_SELECT_APPLICATION, stringToParcel},
{RIL_REQUEST_UICC_DEACTIVATE_APPLICATION, intsToParcel},
{RIL_REQUEST_UICC_APPLICATION_IO, uiccIoToParcel},
{RIL_REQUEST_UICC_AKA_AUTHENTICATE, uiccAuthenticationToParcel},
{RIL_REQUEST_UICC_GBA_AUTHENTICATE_BOOTSTRAP, uiccAuthenticationToParcel},
{RIL_REQUEST_UICC_GBA_AUTHENTICATE_NAF, uiccAuthenticationToParcel},
{RIL_REQUEST_STK_EVDL_CALL_BY_AP, intsToParcel},
{RIL_REQUEST_GET_FEMTOCELL_LIST, stringsToParcel},
// Femtocell (CSG) : abort command shall be sent in differenent channel
{RIL_REQUEST_ABORT_FEMTOCELL_LIST, voidToParcel},
{RIL_REQUEST_SELECT_FEMTOCELL, stringsToParcel},
{RIL_REQUEST_SEND_OPLMN, stringToParcel},
{RIL_REQUEST_GET_OPLMN_VERSION, voidToParcel},
{RIL_REQUEST_ABORT_QUERY_AVAILABLE_NETWORKS , voidToParcel},
{RIL_REQUEST_DIAL_UP_CSD, stringsToParcel},
{RIL_REQUEST_SET_TELEPHONY_MODE, intsToParcel},
{RIL_REQUEST_HANGUP_ALL, voidToParcel},
{RIL_REQUEST_FORCE_RELEASE_CALL, intsToParcel},
{RIL_REQUEST_SET_CALL_INDICATION, intsToParcel},
{RIL_REQUEST_EMERGENCY_DIAL, dialToParcel},
{RIL_REQUEST_SET_ECC_SERVICE_CATEGORY, intsToParcel},
{RIL_REQUEST_SET_ECC_LIST, stringsToParcel},
{RIL_REQUEST_GENERAL_SIM_AUTH, simAuthToParcel},
{RIL_REQUEST_OPEN_ICC_APPLICATION, intsToParcel},
{RIL_REQUEST_GET_ICC_APPLICATION_STATUS, intsToParcel},
{RIL_REQUEST_SIM_IO_EX, sim_IO_EXToParcel},
{RIL_REQUEST_SET_IMS_ENABLE, intsToParcel},
{RIL_REQUEST_QUERY_AVAILABLE_NETWORKS_WITH_ACT , voidToParcel},
{RIL_REQUEST_SEND_CNAP, voidToParcel},
{RIL_REQUEST_SET_CLIP, intsToParcel},
{RIL_REQUEST_SETUP_DEDICATE_DATA_CALL, setupDedicateDataCallToParcel},
{RIL_REQUEST_DEACTIVATE_DEDICATE_DATA_CALL, stringsToParcel},
{RIL_REQUEST_MODIFY_DATA_CALL, modifyDedicateDataCallToParcel},
{RIL_REQUEST_ABORT_SETUP_DATA_CALL, stringsToParcel},
{RIL_REQUEST_PCSCF_DISCOVERY_PCO, intsToParcel},
{RIL_REQUEST_CLEAR_DATA_BEARER, voidToParcel},
{RIL_REQUEST_REMOVE_CB_MESSAGE, intsToParcel},
{RIL_REQUEST_SET_DATA_CENTRIC, intsToParcel},
{RIL_REQUEST_ADD_IMS_CONFERENCE_CALL_MEMBER, stringsToParcel},
{RIL_REQUEST_REMOVE_IMS_CONFERENCE_CALL_MEMBER, stringsToParcel},
{RIL_REQUEST_DIAL_WITH_SIP_URI, stringToParcel},
{RIL_REQUEST_RESUME_CALL, intsToParcel},
{RIL_REQUEST_SET_SPEECH_CODEC_INFO, intsToParcel},
{RIL_REQUEST_SET_DATA_ON_TO_MD, intsToParcel},
{RIL_REQUEST_SET_REMOVE_RESTRICT_EUTRAN_MODE, intsToParcel},
{RIL_REQUEST_SET_IMS_CALL_STATUS, intsToParcel},
{RIL_REQUEST_VT_DIAL, dialToParcel},
{RIL_REQUEST_VOICE_ACCEPT, intsToParcel},
{RIL_REQUEST_REPLACE_VT_CALL, intsToParcel},
{RIL_REQUEST_CONFIG_MODEM_STATUS, intsToParcel},
/// M: [C2K] MD IRAT feature. @{
{RIL_REQUEST_SET_ACTIVE_PS_SLOT, intsToParcel},
{RIL_REQUEST_CONFIRM_INTER_3GPP_IRAT_CHANGE, intsToParcel},
/// @}
/// M: [C2K][SVLTE] Set the SVLTE RAT mode. @{
{RIL_REQUEST_SET_SVLTE_RAT_MODE, intsToParcel},
/// M: [C2K][SVLTE] Set the SVLTE RAT mode. @}
/// M: [C2K] AP IRAT feature. @{
{RIL_REQUEST_TRIGGER_LTE_BG_SEARCH, intsToParcel},
/// @}
{RIL_REQUEST_CONFERENCE_DIAL, stringsToParcel},
/// M: CC072: Add Customer proprietary-IMS RIL interface. @{
{RIL_REQUEST_SET_SRVCC_CALL_CONTEXT_TRANSFER, stringsToParcel},
{RIL_REQUEST_UPDATE_IMS_REGISTRATION_STATUS, intsToParcel},
{RIL_REQUEST_RELOAD_MODEM_TYPE, intsToParcel},
/// @}
/// M: IMS feature. @{
{RIL_REQUEST_HOLD_CALL, intsToParcel},
/// @}
{RIL_REQUEST_SET_STK_UTK_MODE, intsToParcel},
{RIL_REQUEST_SWITCH_ANTENNA, intsToParcel},

// M: [C2K] Deactivate link down PDN for CT requirement. @{
{RIL_REQUEST_DEACTIVATE_LINK_DOWN_PDN, voidToParcel},
// @}
{RIL_REQUEST_AT_COMMAND_WITH_PROXY, rawToParcel},
{RIL_REQUEST_SWITCH_CARD_TYPE, intsToParcel},
{RIL_REQUEST_ENABLE_MD3_SLEEP, intsToParcel},
/// M: ViLTE. @{
{RIL_REQUEST_VIDEO_CALL_ACCEPT, intsToParcel},
/// @}
// M: [LTE][Low Power][UL traffic shaping] Start
{RIL_REQUEST_SET_LTE_ACCESS_STRATUM_REPORT, intsToParcel},
{RIL_REQUEST_SET_LTE_UPLINK_DATA_TRANSFER, intsToParcel},
// M: [LTE][Low Power][UL traffic shaping] End
/// M: [EPDG] Hand over ind @{
{RIL_REQUEST_HANDOVER_IND, intsToParcel},
/// M: [EPDG] Hand over ind @}
/// M: USSI RIL request commands @{
{RIL_REQUEST_SEND_USSI, stringsToParcel},
{RIL_REQUEST_CANCEL_USSI, voidToParcel},
/// @}
// Merge C2K only Commands
{RIL_REQUEST_GET_NITZ_TIME, voidToParcel},
{RIL_REQUEST_QUERY_UIM_INSERTED, voidToParcel},
{RIL_REQUEST_SWITCH_HPF, intsToParcel},
{RIL_REQUEST_SET_AVOID_SYS, intsToParcel},
{RIL_REQUEST_QUERY_AVOID_SYS, voidToParcel},
{RIL_REQUEST_QUERY_CDMA_NETWORK_INFO, voidToParcel},
{RIL_REQUEST_GET_LOCAL_INFO, voidToParcel},
{RIL_REQUEST_UTK_REFRESH, intsToParcel},
{RIL_REQUEST_QUERY_SMS_AND_PHONEBOOK_STATUS, voidToParcel},
{RIL_REQUEST_QUERY_NETWORK_REGISTRATION, voidToParcel},
{RIL_REQUEST_AGPS_TCP_CONNIND, intsToParcel},
{RIL_REQUEST_AGPS_SET_MPC_IPPORT, stringsToParcel},
{RIL_REQUEST_AGPS_GET_MPC_IPPORT, voidToParcel},
{RIL_REQUEST_SET_MEID, stringToParcel},
{RIL_REQUEST_RESUME_REGISTRATION_CDMA, voidToParcel},
{RIL_REQUEST_SET_REG_SUSPEND_ENABLED_CDMA, intsToParcel},
{RIL_REQUEST_SET_ETS_DEV, intsToParcel},
{RIL_REQUEST_WRITE_MDN, stringToParcel},
{RIL_REQUEST_SET_VIA_TRM, intsToParcel},
{RIL_REQUEST_SET_ARSI_THRESHOLD, intsToParcel},
{RIL_REQUEST_SET_LTE_EARFCN_ENABLED, intsToParcel},
{RIL_REQUEST_CONFIG_IRAT_MODE, intsToParcel},
{RIL_REQUEST_QUERY_UTK_MENU_FROM_MD, voidToParcel},
{RIL_REQUEST_QUERY_STK_MENU_FROM_MD, voidToParcel},
{RIL_REQUEST_CONFIG_EVDO_MODE, intsToParcel},
{RIL_REQUEST_AT_COMMAND_WITH_PROXY_CDMA, rawToParcel},
// @}
/// M: [EPDG] Wifi disconnect indication @{
{RIL_REQUEST_WIFI_DISCONNECT_IND, stringsToParcel},
{RIL_REQUEST_MAL_PS_RGEGISTRATION_STATE, stringToParcel},
/// @}
