/*
*  Copyright (C) 2014 MediaTek Inc.
*
*  Modification based on code covered by the below mentioned copyright
*  and/or permission notice(s).
*/


/* //hardware/ril/librilmtk/ril_commands.h
**
** Copyright 2014, The Android Open Source Project
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
*/
    {0, NULL},                   // none
    {RIL_REQUEST_GET_SIM_STATUS, voidToParcel},
    {RIL_REQUEST_ENTER_SIM_PIN, stringsToParcel},
    {RIL_REQUEST_ENTER_SIM_PUK, stringsToParcel},
    {RIL_REQUEST_ENTER_SIM_PIN2, stringsToParcel},
    {RIL_REQUEST_ENTER_SIM_PUK2, stringsToParcel},
    {RIL_REQUEST_CHANGE_SIM_PIN, stringsToParcel},
    {RIL_REQUEST_CHANGE_SIM_PIN2, stringsToParcel},
    {RIL_REQUEST_ENTER_NETWORK_DEPERSONALIZATION, stringsToParcel},
    {RIL_REQUEST_GET_CURRENT_CALLS, voidToParcel},
    {RIL_REQUEST_DIAL, dialToParcel},
    {RIL_REQUEST_GET_IMSI, stringsToParcel},
    {RIL_REQUEST_HANGUP, intsToParcel},
    {RIL_REQUEST_HANGUP_WAITING_OR_BACKGROUND, voidToParcel},
    {RIL_REQUEST_HANGUP_FOREGROUND_RESUME_BACKGROUND, voidToParcel},
    {RIL_REQUEST_SWITCH_WAITING_OR_HOLDING_AND_ACTIVE, voidToParcel},
    {RIL_REQUEST_CONFERENCE, voidToParcel},
    {RIL_REQUEST_UDUB, voidToParcel},
    {RIL_REQUEST_LAST_CALL_FAIL_CAUSE, voidToParcel},
    {RIL_REQUEST_SIGNAL_STRENGTH, voidToParcel},
    {RIL_REQUEST_VOICE_REGISTRATION_STATE, voidToParcel},
    {RIL_REQUEST_DATA_REGISTRATION_STATE, voidToParcel},
    {RIL_REQUEST_OPERATOR, voidToParcel},
    {RIL_REQUEST_RADIO_POWER, intsToParcel},
    {RIL_REQUEST_DTMF, stringToParcel},
    {RIL_REQUEST_SEND_SMS, stringsToParcel},
    {RIL_REQUEST_SEND_SMS_EXPECT_MORE, stringsToParcel},
    {RIL_REQUEST_SETUP_DATA_CALL, dataCallToParcel},
    {RIL_REQUEST_SIM_IO, sim_IOToParcel},
    {RIL_REQUEST_SEND_USSD, stringToParcel},
    {RIL_REQUEST_CANCEL_USSD, voidToParcel},
    {RIL_REQUEST_GET_CLIR, voidToParcel},
    {RIL_REQUEST_SET_CLIR, intsToParcel},
    {RIL_REQUEST_QUERY_CALL_FORWARD_STATUS, callForwardToParcel},
    {RIL_REQUEST_SET_CALL_FORWARD, callForwardToParcel},
    {RIL_REQUEST_QUERY_CALL_WAITING, intsToParcel},
    {RIL_REQUEST_SET_CALL_WAITING, intsToParcel},
    {RIL_REQUEST_SMS_ACKNOWLEDGE, intsToParcel},
    {RIL_REQUEST_GET_IMEI, voidToParcel},
    {RIL_REQUEST_GET_IMEISV, voidToParcel},
    {RIL_REQUEST_ANSWER, voidToParcel},
    {RIL_REQUEST_DEACTIVATE_DATA_CALL, stringsToParcel},
    {RIL_REQUEST_QUERY_FACILITY_LOCK, stringsToParcel},
    {RIL_REQUEST_SET_FACILITY_LOCK, stringsToParcel},
    {RIL_REQUEST_CHANGE_BARRING_PASSWORD, stringsToParcel},
    {RIL_REQUEST_QUERY_NETWORK_SELECTION_MODE, voidToParcel},
    {RIL_REQUEST_SET_NETWORK_SELECTION_AUTOMATIC, voidToParcel},
    {RIL_REQUEST_SET_NETWORK_SELECTION_MANUAL, stringToParcel},
    {RIL_REQUEST_QUERY_AVAILABLE_NETWORKS , voidToParcel},
    {RIL_REQUEST_DTMF_START, stringToParcel},
    {RIL_REQUEST_DTMF_STOP, voidToParcel},
    {RIL_REQUEST_BASEBAND_VERSION, voidToParcel},
    {RIL_REQUEST_SEPARATE_CONNECTION, intsToParcel},
    {RIL_REQUEST_SET_MUTE, intsToParcel},
    {RIL_REQUEST_GET_MUTE, voidToParcel},
    {RIL_REQUEST_QUERY_CLIP, voidToParcel},
    {RIL_REQUEST_LAST_DATA_CALL_FAIL_CAUSE, voidToParcel},
    {RIL_REQUEST_DATA_CALL_LIST, voidToParcel},
    {RIL_REQUEST_RESET_RADIO, voidToParcel},
    {RIL_REQUEST_OEM_HOOK_RAW, rawToParcel},
    {RIL_REQUEST_OEM_HOOK_STRINGS, stringsToParcel},
    {RIL_REQUEST_SCREEN_STATE, intsToParcel},
    {RIL_REQUEST_SET_SUPP_SVC_NOTIFICATION, intsToParcel},
    {RIL_REQUEST_WRITE_SMS_TO_SIM, smsWriteToParcel},
    {RIL_REQUEST_DELETE_SMS_ON_SIM, intsToParcel},
    {RIL_REQUEST_SET_BAND_MODE, intsToParcel},
    {RIL_REQUEST_QUERY_AVAILABLE_BAND_MODE, voidToParcel},
    {RIL_REQUEST_STK_GET_PROFILE, voidToParcel},
    {RIL_REQUEST_STK_SET_PROFILE, stringToParcel},
    {RIL_REQUEST_STK_SEND_ENVELOPE_COMMAND, stringToParcel},
    {RIL_REQUEST_STK_SEND_TERMINAL_RESPONSE, stringToParcel},
    {RIL_REQUEST_STK_HANDLE_CALL_SETUP_REQUESTED_FROM_SIM, intsToParcel},
    {RIL_REQUEST_EXPLICIT_CALL_TRANSFER, voidToParcel},
    {RIL_REQUEST_SET_PREFERRED_NETWORK_TYPE, intsToParcel},
    {RIL_REQUEST_GET_PREFERRED_NETWORK_TYPE, voidToParcel},
    {RIL_REQUEST_GET_NEIGHBORING_CELL_IDS, voidToParcel},
    {RIL_REQUEST_SET_LOCATION_UPDATES, intsToParcel},
    {RIL_REQUEST_CDMA_SET_SUBSCRIPTION_SOURCE, intsToParcel},
    {RIL_REQUEST_CDMA_SET_ROAMING_PREFERENCE, intsToParcel},
    {RIL_REQUEST_CDMA_QUERY_ROAMING_PREFERENCE, voidToParcel},
    {RIL_REQUEST_SET_TTY_MODE, intsToParcel},
    {RIL_REQUEST_QUERY_TTY_MODE, voidToParcel},
    {RIL_REQUEST_CDMA_SET_PREFERRED_VOICE_PRIVACY_MODE, intsToParcel},
    {RIL_REQUEST_CDMA_QUERY_PREFERRED_VOICE_PRIVACY_MODE, voidToParcel},
    {RIL_REQUEST_CDMA_FLASH, stringToParcel},
    {RIL_REQUEST_CDMA_BURST_DTMF, stringsToParcel},
    {RIL_REQUEST_CDMA_VALIDATE_AND_WRITE_AKEY, stringToParcel},
    {RIL_REQUEST_CDMA_SEND_SMS, cdmaSmsToParcel},
    {RIL_REQUEST_CDMA_SMS_ACKNOWLEDGE, cdmaSmsAckToParcel},
    {RIL_REQUEST_GSM_GET_BROADCAST_SMS_CONFIG, voidToParcel},
    {RIL_REQUEST_GSM_SET_BROADCAST_SMS_CONFIG, gsmBrSmsCnfToParcel},
    {RIL_REQUEST_GSM_SMS_BROADCAST_ACTIVATION, intsToParcel},
    {RIL_REQUEST_CDMA_GET_BROADCAST_SMS_CONFIG, voidToParcel},
    {RIL_REQUEST_CDMA_SET_BROADCAST_SMS_CONFIG, cdmaBrSmsCnfToParcel},
    {RIL_REQUEST_CDMA_SMS_BROADCAST_ACTIVATION, intsToParcel},
    {RIL_REQUEST_CDMA_SUBSCRIPTION, voidToParcel},
    {RIL_REQUEST_CDMA_WRITE_SMS_TO_RUIM, rilCdmaSmsWriteArgsToParcel},
    {RIL_REQUEST_CDMA_DELETE_SMS_ON_RUIM, intsToParcel},
    {RIL_REQUEST_DEVICE_IDENTITY, voidToParcel},
    {RIL_REQUEST_EXIT_EMERGENCY_CALLBACK_MODE, voidToParcel},
    {RIL_REQUEST_GET_SMSC_ADDRESS, voidToParcel},
    {RIL_REQUEST_SET_SMSC_ADDRESS, stringToParcel},
    {RIL_REQUEST_REPORT_SMS_MEMORY_STATUS, intsToParcel},
    {RIL_REQUEST_REPORT_STK_SERVICE_IS_RUNNING, voidToParcel},
    {RIL_REQUEST_CDMA_GET_SUBSCRIPTION_SOURCE, cdmaSubscriptionSourceToParcel},
    {RIL_REQUEST_ISIM_AUTHENTICATION, stringToParcel},
    {RIL_REQUEST_ACKNOWLEDGE_INCOMING_GSM_SMS_WITH_PDU, stringsToParcel},
    {RIL_REQUEST_STK_SEND_ENVELOPE_WITH_STATUS, stringToParcel},
    {RIL_REQUEST_VOICE_RADIO_TECH, voiceRadioTechToParcel},
    {RIL_REQUEST_GET_CELL_INFO_LIST, voidToParcel},
    {RIL_REQUEST_SET_UNSOL_CELL_INFO_LIST_RATE, intsToParcel},
    {RIL_REQUEST_SET_INITIAL_ATTACH_APN, setInitialAttachApnToParcel},
    {RIL_REQUEST_IMS_REGISTRATION_STATE, voidToParcel},
    {RIL_REQUEST_IMS_SEND_SMS, imsSmsToParcel},
    {RIL_REQUEST_SIM_TRANSMIT_APDU_BASIC, sim_APDUToParcel},
    {RIL_REQUEST_SIM_OPEN_CHANNEL, stringToParcel},
    {RIL_REQUEST_SIM_CLOSE_CHANNEL, intsToParcel},
    {RIL_REQUEST_SIM_TRANSMIT_APDU_CHANNEL, sim_APDUToParcel},
    {RIL_REQUEST_NV_READ_ITEM, nvReadItemToParcel},
    {RIL_REQUEST_NV_WRITE_ITEM, nvWriteItemToParcel},
    {RIL_REQUEST_NV_WRITE_CDMA_PRL, rawToParcel},
    {RIL_REQUEST_NV_RESET_CONFIG, intsToParcel},
    {RIL_REQUEST_SET_UICC_SUBSCRIPTION, uiccSubscriptonToParcel},
    {RIL_REQUEST_ALLOW_DATA, intsToParcel},
    {RIL_REQUEST_GET_HARDWARE_CONFIG, voidToParcel},
    {RIL_REQUEST_SIM_AUTHENTICATION, simAuthenticationToParcel},
    {RIL_REQUEST_GET_DC_RT_INFO, voidToParcel},
    {RIL_REQUEST_SET_DC_RT_INFO_RATE, intsToParcel},
    {RIL_REQUEST_SET_DATA_PROFILE, dataProfileToParcel},
    {RIL_REQUEST_SHUTDOWN, voidToParcel},
    {RIL_REQUEST_GET_RADIO_CAPABILITY, voidToParcel},
    {RIL_REQUEST_SET_RADIO_CAPABILITY, radioCapabilityToParcel},
    {RIL_REQUEST_START_LCE, intsToParcel},
    {RIL_REQUEST_STOP_LCE, voidToParcel},
    {RIL_REQUEST_PULL_LCEDATA, voidToParcel},
    {RIL_REQUEST_GET_ACTIVITY_INFO, voidToParcel},
    {RIL_REQUEST_OEM_HOOK_RAW_REDIRECT, rawToParcel},