LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE =
LOCAL_MODULE = com_mediatek_amplus
LOCAL_MODULE_CLASS = JAVA_LIBRARIES
LOCAL_MODULE_PATH =
LOCAL_MODULE_RELATIVE_PATH =
LOCAL_MODULE_SUFFIX = .jar
LOCAL_SRC_FILES = javalib.jar
include $(BUILD_PREBUILT)
