# Copyright Statement:
#
# This software/firmware and related documentation ("MediaTek Software") are
# protected under relevant copyright laws. The information contained herein
# is confidential and proprietary to MediaTek Inc. and/or its licensors.
# Without the prior written permission of MediaTek inc. and/or its licensors,
# any reproduction, modification, use or disclosure of MediaTek Software,
# and information contained herein, in whole or in part, shall be strictly prohibited.

# MediaTek Inc. (C) 2010. All rights reserved.
#
# BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
# THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
# RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
# AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
# NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
# SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
# SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
# THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
# THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
# CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
# SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
# STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
# CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
# AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
# OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
# MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
#
# The following software/firmware and/or related documentation ("MediaTek Software")
# have been modified by MediaTek Inc. All revisions are subject to any receiver's
# applicable license agreements with MediaTek Inc.


ifeq ($(MTK_PLATFORM),MT8163)
# Deump debug information of build enviornment
$(info Ptgen Env of Andorid)
$(info value of MTK_PLATFORM is: $(MTK_PLATFORM))
$(info value of PRODUCT_OUT is: $(PRODUCT_OUT))
$(info value of TARGET_OUT_INTERMEDIATES is: $(TARGET_OUT_INTERMEDIATES))
$(info value of MTK_TARGET_PROJECT is: $(MTK_TARGET_PROJECT))
$(info value of PLATFORM is: $(PLATFORM))
$(info value of MTK_PROJECT is: $(MTK_PROJECT))
$(info value of MTK_ATF_SUPPORT is: $(MTK_ATF_SUPPORT))
$(info value of MTK_TEE_SUPPORT is: $(MTK_TEE_SUPPORT))


#input file for ptgen
ifeq ($(MTK_GPT_SCHEME_SUPPORT),yes)
PTGEN_PERL = device/mediatek/build/build/tools/ptgen/$(MTK_PLATFORM)/ptgen.pl
else
PTGEN_PERL = device/mediatek/build/build/tools/ptgen/$(MTK_PLATFORM)/ptgen_pmt.pl
PTGENXLS_PERL = ./device/mediatek/build/build/tools/ptgen/$(MTK_PLATFORM)/ptgen_xls.pl
endif

OTA_SCATTER_PERL = device/mediatek/build/build/tools/ptgen/ota_scatter.pl
CHIP = $(shell echo $(TARGET_BOARD_PLATFORM) | tr '[a-z]' '[A-Z]')

ifneq ($(MTK_GPT_SCHEME_SUPPORT),yes)
#find the associated partition table from project setting
PTGEN_XLS:=$(shell PLATFORM=${MTK_PLATFORM} PROJECT=${MTK_TARGET_PROJECT} perl ${PTGENXLS_PERL})
endif

#outpath
PTGEN_PROJECT_OUT:=$(PRODUCT_OUT)
PTGEN_MK_OUT=${TARGET_OUT_INTERMEDIATES}/PTGEN

ifneq ($(MTK_GPT_SCHEME_SUPPORT),yes)
TMP_OUT_PATH=${TARGET_OUT_INTERMEDIATES}/PTGEN_TEMP
endif

droidcore: $(PTGEN_MK_OUT)/partition_size.mk
ptgen: $(PTGEN_MK_OUT)/partition_size.mk

$(PTGEN_MK_OUT)/partition_size.mk:
	@PLATFORM=${MTK_PLATFORM} \
	MTK_TARGET_PROJECT=${MTK_TARGET_PROJECT} \
	TARGET_BUILD_VARIANT=${TARGET_BUILD_VARIANT} \
	MTK_NAND_PAGE_SIZE=${MTK_NAND_PAGE_SIZE} \
	MTK_EMMC_SUPPORT=${MTK_EMMC_SUPPORT} \
	MTK_TC1_FEATURE=${MTK_TC1_FEATURE} \
	MTK_LDVT_SUPPORT=${MTK_LDVT_SUPPORT} \
	MTK_EMMC_SUPPORT_OTP=${MTK_EMMC_SUPPORT_OTP} \
	MTK_SHARED_SDCARD=${MTK_SHARED_SDCARD} \
	MTK_CIP_SUPPORT=${MTK_CIP_SUPPORT} \
	MTK_FAT_ON_NAND=${MTK_FAT_ON_NAND} \
	MTK_SPI_NAND_SUPPORT=${MTK_SPI_NAND_SUPPORT} \
	MTK_NAND_UBIFS_SUPPORT=${MTK_NAND_UBIFS_SUPPORT} \
	MTK_COMBO_NAND_SUPPORT=${MTK_COMBO_NAND_SUPPORT} \
	PL_MODE=${PL_MODE} \
	MTK_PARTITION_TABLE_PLAIN_TEXT=${MTK_PARTITION_TABLE_PLAIN_TEXT} \
	MTK_ATF_SUPPORT=${MTK_ATF_SUPPORT} \
	MTK_TEE_SUPPORT=${MTK_TEE_SUPPORT} \
	MTK_PERSIST_PARTITION_SUPPORT=${MTK_PERSIST_PARTITION_SUPPORT} \
	MTK_DRM_KEY_MNG_SUPPORT=${MTK_DRM_KEY_MNG_SUPPORT} \
	MTK_BASE_PROJECT=${MTK_BASE_PROJECT} \
	PRELOADER_TARGET_PRODUCT=${PRELOADER_TARGET_PRODUCT} \
	PTGEN_ENV="ANDROID" \
	PTGEN_PROJECT_OUT=${PTGEN_PROJECT_OUT} \
	PTGEN_MK_OUT=${PTGEN_MK_OUT} \
	TMP_OUT_PATH=${TMP_OUT_PATH} \
	perl $(PTGEN_PERL)
	perl $(OTA_SCATTER_PERL) ${PRODUCT_OUT}/$(CHIP)_Android_scatter.txt ${PRODUCT_OUT}/ota_scatter.txt

endif
